name: Translation Automation

on:
  push:
    branches:
      - master

jobs:
  translation-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate random branch name
        id: random_branch
        run: echo "BRANCH=translation-auto-$(uuidgen | cut -d'-' -f1)" >> $GITHUB_ENV

      - name: Create and switch to new branch
        run: |
          git checkout -b $BRANCH

      - name: Make random change to i18n file
        run: |
          FILE=$(find i18n -type f | head -n 1)
          if [ -n "$FILE" ]; then
            echo "# Random change $(date)" >> "$FILE"
            git add "$FILE"
          fi

      - name: Commit changes
        run: |
          git commit -m "Automated translation update"

      - name: Push changes
        run: |
          git push --set-upstream origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          base: master
          title: 'Automated translation update'
          body: 'This PR was created automatically to update translations.'