name: Translation Automation

on:
  push:
    branches: [master]
    paths:
      - 'i18n/**'
  workflow_dispatch:
    inputs:
      target_file:
        description: 'Path to target JSON file (e.g., i18n/en.json)'
        required: false
        default: 'i18n/en.json'

jobs:
  automate-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Create branch
        run: |
          BRANCH_NAME="translation-update/$(date +%Y%m%d%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Ensure target JSON file exists
        run: |
          TARGET_FILE="${{ github.event.inputs.target_file }}"
          if [ -z "$TARGET_FILE" ]; then TARGET_FILE="i18n/en.json"; fi
          mkdir -p i18n
          echo "{\"last_updated\": \"$(date +%Y-%m-%dT%H:%M:%S)\"}" > "$TARGET_FILE"
          echo "Updated $TARGET_FILE"
        shell: bash

      - name: Commit changes
        run: |
          git add i18n/*.json
          git commit -m "Update translation file ${{ github.event.inputs.target_file || 'i18n/en.json' }}" || echo "No changes to commit"
          git push origin ${{ env.BRANCH_NAME }}
        shell: bash

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_FILE="${{ github.event.inputs.target_file }}"
          if [ -z "$PR_FILE" ]; then PR_FILE="i18n/en.json"; fi
          gh pr create --title "Translation Update for $PR_FILE" \
                       --body "Automated update of translation file" \
                       --base main \
                       --head ${{ env.BRANCH_NAME }}
        shell: bash
