name: Translation Automation

on:
  push:
    branches: [master]  
    paths:
      - 'i18n/**'
  workflow_dispatch:
    inputs:
      target_file:
        description: 'Path to target JSON file (e.g., i18n/en.json)'
        required: false
        default: 'i18n/en.json'

jobs:
  automate-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
# github actor
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
#echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
#git checkout -b "$BRANCH_NAME"
      - name: Create branch
        run: |
          BRANCH_NAME="translation-update/$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Ensure target JSON file exists
run: |  
    TARGET_FILE="${{ github.event.inputs.target_file || 'i18n/en.json' }}"  
    mkdir -p i18n  
    echo "{\"last_updated\": \"$(date +%Y-%m-%dT%H:%M:%S)\"}" > "$TARGET_FILE"  
    echo "Updated $TARGET_FILE"
        shell: bash
#push origin ${{ steps.branch.outputs.branch }}
      - name: Commit changes
        run: |
          git add i18n/*.json
          git commit -m "Update translation file ${{ github.event.inputs.target_file || 'i18n/en.json' }}" || echo "No changes to commit"
          git push origin ${{ env.BRANCH_NAME }}
        shell: bash
#--head ${{ steps.branch.outputs.branch }}

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Translation Update for ${{ github.event.inputs.target_file || 'i18n/en.json' }}" \
                       --body "Automated update of translation file" \
                       --base main \
                       --head ${{ env.BRANCH_NAME }}
        shell: bash
