name: Create PR with i18n File Uploads

on:
  push:
    branches:
      - translation-temp  # Triggers when translation files are pushed here

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and switch to a new feature branch
        run: |
          BRANCH_NAME=i18n-update-${{ github.run_number }}
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Checkout translation-temp branch to fetch all .json files
        uses: actions/checkout@v4
        with:
          ref: translation-temp
          path: temp-json

      - name: Copy translation files into i18n/ and delete originals
        run: |
          mkdir -p i18n
          find temp-json -maxdepth 1 -name '*.json' -exec cp {} i18n/ \;
          
          echo "✅ Copied all translation .json files to i18n/"

          # Clean up original .json files (simulate removing them from root)
          find temp-json -maxdepth 1 -name '*.json' -exec rm {} \;
          echo "🧹 Deleted original .json files from temp-json/"

      - name: Commit the updated i18n folder and cleanup
        run: |
          git add i18n/
          git commit -m "chore: Add updated translation JSON files"
          
      - name: Push the feature branch
        run: |
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ env.BRANCH_NAME }}
          target_branch: master
          title: "Add Translations - ${{ env.BRANCH_NAME }}"
          body: |
            This PR adds translated JSON files into the i18n/ folder.
            The original files from the translation-temp branch have been cleaned up.
